name: Supervisor Docker Image

on:
  workflow_dispatch:
  push:
    branches: 
      - "main"
    tags:
      - "v*"  # Push events to matching v*, i.e. v1.0, v20.15.10

env:
  IMAGE_NAME: ghcr.io/liquidai-project/wasmiot-supervisor
  PLATFORMS: linux/amd64,linux/arm64

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into registry
        # if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get container meta information
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            # set latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}
            # output 0.1.2
            type=semver,pattern={{version}}
            # output 0.1
            type=semver,pattern={{major}}.{{minor}}
            # branch
            type=ref,event=branch

      - name: Build and push fileserv
        uses: docker/build-push-action@v4
        with:
          context: .
          target: base
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push devcontainer when pushing to main
        uses: devcontainers/ci@v0.3
        if: github.ref == 'refs/heads/main'
        with:
          eventFilterForPush:

          cacheFrom: ${{ env.IMAGE_NAME }}:${{ github.ref_name }}
          imageName: ${{ env.IMAGE_NAME }}
          imageTag: devcontainer
