description: |
  Solution for how the manifest is to be enacted based on
  manifest and available resources
type: object
required:
  - nodes
properties:
  nodes:
    type: array
    items:
      $ref: "./DeploymentNode.yml"

