version: '3.4'

services:
  orchestrator-ipvlan:
    extends:
      file: docker-compose.yml
      service: orchestrator-base
    restart: always
    networks:
      default:
      dockeripvlan:
      nginx-net:
    env_file:
      - ./.env.example
      - ./.env

  mongo:
    extends:
      file: docker-compose.yml
      service: mongo

  nginx:
    image: nginx:1.25
    restart: unless-stopped
    ports:
      - ${PUBLIC_PORT:-3000}:3000
    volumes:
      - ./nginx:/etc/nginx:ro
    networks:
      nginx-net:

volumes:
  mongo-config:
  mongo-db:

networks:
  default:
    name: wasmiot-net
  nginx-net:
    # network for forwarding requests from outside to the orchestrator
    name: wasmiot-nginx
  dockeripvlan:
    # Network for connecting orchestrator server and device discovery to
    # outside from Docker.
    name: dockeripvlan
    driver: ipvlan
    driver_opts:
      parent: ${NETWORK_INTERFACE} #eno1 #wlp0s20f3
    ipam:
      config:
        - subnet: "${NETWORK_IP_BASE}.0/24"
