services:
  # TODO Set IOT-device hostnames to end with ".local."? Considered using `domainname`
  # (see https://docs.docker.com/compose/compose-file/#domainname) but had no
  # luck.
  #
  device-base:
    profiles:
      # NOTE: This makes it so that the service can be extended and the
      # ::OVERRIDE::-marked settings overridden without starting this service
      # during `docker compose up`. The "inherited" services need to be started
      # on their own though (separate profile)...
      - ABSTRACT_BASE_HACK_DO_NOT_USE
    image: ghcr.io/liquidai-project/wasmiot-supervisor
    # ports:
    #   # 5000 is the default Flask-port that is probably used.
    #   - 0:5000 # ::OVERRIDE::
    volumes:
      - type: bind
        source: ./wasmiot-supervisor/host_app
        target: /app/host_app

    env_file:
      - .env.example
      - .env

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 1m30s
      timeout: 30s
      retries: 3
      start_period: 30s

  adequate-webcam-laptop:
    extends: device-base
    profiles:
      - device
    environment:
      - DEVICE_TYPE='webcam-laptop'
      - FLASK_APP='adequate-webcam-laptop'
    ports:
      - 3001:5000
    # NOTE: This is needed to access webcam of Linux hosts.
    privileged: true
    volumes:
      - ./example/device1/configs:/app/instance/configs
      - ./example/device1/modules:/app/instance/modules
      - ./example/device1/output:/app/instance/output
    networks:
      default:
        ipv4_address: 172.15.0.21
    deploy:
      # Simulate constrained memory. See
      # https://docs.docker.com/config/containers/resource_constraints/
      # https://docs.docker.com/compose/compose-file/compose-file-v3/#resources
      resources:
        limits:
          cpus: '0.5'
          # Minimum would be 6 megabytes '6M'.
          memory: 8G


  lousy-webcam-laptop:
    extends: device-base
    profiles:
      - device
    environment:
      - DEVICE_TYPE='webcam-laptop'
      - FLASK_APP='lousy-webcam-laptop'
    ports:
      - 3002:5000
    # NOTE: This is needed to access webcam of Linux hosts.
    privileged: true
    volumes:
      - ./example/device2/configs:/app/instance/configs
      - ./example/device2/modules:/app/instance/modules
      - ./example/device2/output:/app/instance/output
    networks:
      default:
        ipv4_address: 172.15.0.22
    devices:
      - /dev/video0:/dev/video0
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 8G


  low-power-temperature-sensor:
    extends: device-base
    profiles:
      - device
    environment:
      - DEVICE_TYPE='temperature-sensor'
      - FLASK_APP='basic-temperature-sensor'
    ports:
      - 3003:5000
    volumes:
      - ./example/device3/configs:/app/instance/configs
      - ./example/device3/modules:/app/instance/modules
      - ./example/device3/output:/app/instance/output
    networks:
      default:
        ipv4_address: 172.15.0.23
    deploy:
      resources:
        limits:
          cpus: '0.1'
          # NOTE: It seems that at <40M the container shuts down soon after
          # startup with 'Exited(137)'
          memory: 50M

networks:
  default:
    name: wasmiot-net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.15.0.0/24
